<?php

$spanish = array(
    "langCode"               => "es",
    "pageDoesNotExist"       => "Página no encontrada.",

    "dieFreieSeekarte"       => "La Carta Náutica libre",

    // Menu ---------------------------------------------------------
    "Seekarte"               => "Carta Náutica",
    "Vollbild"               => "Pantalla completa",
    "VollbildAnzeigen"       => "Mostrar a pantalla completa",
    "SeaChart"               => "Carta Náutica",
    "ÜberOpenSeaMap"         => "Acerca de OpenSeaMap",
    "Impressum"              => "Apartado legal",
    "Startseite"             => "Página de inicio",
    "ÄhnlicheProjekte"       => "Proyectos similares",
    "SomeRights"             => "Este trabajo está bajo la licencia Creative Commons Attribution-ShareAlike 2.0",

    // Buttons-------------------------------------------------------
    "save"                   => "Grabar",
    "ok"                     => "OK",
    "cancel"                 => "Cancelar",
    "close"                  => "Cerrar",
    "reload"                 => "Recargar",
    "edit"                   => "Editar",
    "move"                   => "Mover",
    "delete"                 => "Eliminar",
    "login"                  => "Entrar",
    "logout"                 => "Salir",
    "createAccount"          => "Crear nueva cuenta",
    "help"                   => "Ayuda",
    "language"               => "Idioma",

    // Weather-------------------------------------------------------
    "weather"                => "Meteo",
    "time"                   => "Hora",
    "wind"                   => "Viento",
    "AirPressure"            => "Presión",
    "AirTemperature"         => "Temperatura",
    "precipitation"          => "Precipitatión",
    "WaveHeight"             => "Altura de onda",

    // Editor--------------------------------------------------------
    "add"                    => "Añadir",
    "data"                   => "Datos",
    "unknown"                => "Desconocido",
    "comment"                => "Comentario",
    "logged_in"              => "Bienvenido",
    "logged_out"             => "Debes validarte como usuario para poder editar la carta náutica.",
    "logged_out_save"        => "Debes estar validado para grabar los datos.",
    "enterComment"           => "Por favor, introduzca un comentario",
    "positionSeamark"        => "Posición de la baliza.",
    "userName"               => "Usuario",
    "password"               => "Contraseña",
    "dataLoad"               => "Cargando datos...",
    "dataSave"               => "Grabando datos...",
    "changesetCreate"        => "Creando conjunto de cambios...",
    "changesetClose"         => "Cerrando conjunto de cambios...",
    "seamarkAdd"             => "Añadir baliza",
    "seamarkEdit"            => "Editar baliza",
    "seamarkDelete"          => "Eliminar baliza",
    "seamarkMove"            => "Mover baliza",
    "seamarkSave"            => "Grabar baliza",
    "seamarkCategory"        => "Categoría de balizas",
    "seamarkType"            => "Capa de balizas",
    "seamarkName"            => "Nombre de la baliza",
    "comboUnknown"           => "Desconocido- - - - - - - - - - - - -",
    "comboSafeWater"         => "Aguas seguras",
    "comboPort"              => "Babor",
    "comboStarboard"         => "Estribor",
    "comboPrefPort"          => "Preferido: babor",
    "comboPrefStarboard"     => "Preferido: estribor",
    "comboNorth"             => "Cardinal Norte",
    "comboEast"              => "Cardinal Este",
    "comboSouth"             => "Cardinal Sur",
    "comboWest"              => "Cardinal Oeste",
    "comboIsolatedDanger"    => "Peligro aislado",
    "comboSpecialPurpose"    => "Propósito especial",
    "sphere"                 => "Esférica",
    "conical"                => "Cónica",
    "can"                    => "Bidón",
    "barrel"                 => "Tonel",
    "pillar"                 => "Pilar",
    "spar"                   => "Mástil",
    "beacon"                 => "Baliza",
    "topmark"                => "Señal de tope",
    "radar"                  => "Reflector rádar",
    "lighted"                => "Fanal",
    "fogsignal"              => "Señal de niebla",
    "miscItems"              => "Más <br>propiedades",
    "colour"                 => "Color",
    "red"                    => "rojo",
    "yellow"                 => "amarillo",
    "character"              => "Carácter",
    "period"                 => "Periodo",
    "haveAccount"            => "¿No tienes una cuenta<br/>de OSM aún? ",

    //Network -------------------------------------------------------
    "send401"                => "Validación fallida: ¡Nombre de usuario o contraseña incorrecta!",
    "send404"                => "Grabación fallida: ¡El servidor de la base de datos de OSM no responde!",

    // Urls ---------------------------------------------------------
    "UrlOSM"                 => "http://openstreetmap.org",
    "UrlOSMWiki_Hauptseite"  => "http://wiki.openstreetmap.org/wiki/ES:Main_Page",
    "UrlOSMWiki_OpenSeaMap"  => "http://wiki.openstreetmap.org/wiki/OpenSeaMap",

    // Legende ------------------------------------------------------
    "Legende"                => "Leyenda",
    "Seezeichen"             => "Balizas",
    "Leuchtfeuer"            => "Luces",
    "BrückenSchleusen"       => "Puentes/Esclusas",
    //Harbour
    "harbour"                => "Puerto",
    "breakwater"             => "Rompeolas",
    "pier"                   => "Embarcadero",
    "crane"                  => "Grúa",
    "slipway"                => "Varadero",
    "harbour_master"         => "Práctico",
    "waste_disposal"         => "Eliminación de residuos",
    //Seamarks
    "safe_water"             => "Aguas seguras",
    "lateral_port"           => "Señal de babor",
    "lateral_starboard"      => "Señal de estribor",
    "lateral_pref_port"      => "Canal preferido: babor",
    "lateral_pref_starboard" => "Canal preferido: estribor",
    "cardinal_north"         => "Señal Cardinal Norte",
    "cardinal_east"          => "Señal Cardinal Este",
    "cardinal_south"         => "Señal Cardinal Sur",
    "cardinal_west"          => "Señal Cardinal Oeste",
    "isolated_danger"        => "Señal de peligro aislado",
    "special_purpose"        => "Señal especial",
    //Lights
    "lighthouse"             => "Faro",
    "beacon_green"           => "Baliza verde",
    "beacon_red"             => "Baliza roja",
    "beacon_white"           => "Baliza blanca",
    //Locks
    "lock_gate"              => "Puerta de esclusa",
    "lock"                   => "Esclusa",
    "wier_small"             => "Aliviadero (pequeño)",
    "wier_big"               => "Aliviadero (grande)",
);

?>
