<?php

$russian = array(
    "langCode"               => "ru",
    "pageDoesNotExist"       => "Страница не найдена.",

    "dieFreieSeekarte"       => "Открытая морская карта",

    // Menu ---------------------------------------------------------
    "Seekarte"               => "Карта",
    "Vollbild"               => "На весь экран",
    "VollbildAnzeigen"       => "Показать на весь экран",
    "SeaChart"               => "Карта",
    "ÜberOpenSeaMap"         => "О проекте OpenSeaMap",
    "Impressum"              => "Правовая информация",
    "Startseite"             => "Заглавная страница",
    "ÄhnlicheProjekte"       => "Похожие проекты",
    "SomeRights"             => "Данные распространяются под лицензией Creative Commons Attribution-ShareAlike 2.0",

    // Buttons-------------------------------------------------------
    "save"                   => "Сохранить",
    "ok"                     => "OK",
    "cancel"                 => "Отмена",
    "close"                  => "Закрыть",
    "reload"                 => "Заново загрузить",
    "edit"                   => "Править",
    "move"                   => "Подвинуть",
    "delete"                 => "Удалить",
    "login"                  => "Представиться",
    "logout"                 => "Выйти",
    "createAccount"          => "Создать новый аккаунт",
    "help"                   => "Справка",
    "language"               => "Язык",

    // Weather-------------------------------------------------------
    "weather"                => "Погода",
    "time"                   => "Время",
    "wind"                   => "Ветер",
    "AirPressure"            => "Атмосферное давление",
    "AirTemperature"         => "Температура",
    "precipitation"          => "Осадки",
    "WaveHeight"             => "Высота волны",

    // Editor--------------------------------------------------------
    "add"                    => "Добавить",
    "data"                   => "Данные",
    "unknown"                => "Неизвестно",
    "comment"                => "Комментарий",
    "logged_in"              => "Добро пожаловать",
    "logged_out"             => "Вам надо представиться, чтобы редактировать карту",
    "logged_out_save"        => "Вам надо представиться, чтобы сохранить данные",
    "enterComment"           => "Пожалуйста, напишите комментарий",
    "positionSeamark"        => "Положение знака",
    "userName"               => "Имя пользователя",
    "password"               => "Пароль",
    "dataLoad"               => "Загружаем данные",
    "dataSave"               => "Сохраняем данные",
    "changesetCreate"        => "Открываем сеанс",
    "changesetClose"         => "Закрываем сеанс",
    "seamarkAdd"             => "Добавить знак",
    "seamarkEdit"            => "Править знак",
    "seamarkDelete"          => "Удалить знак",
    "seamarkMove"            => "Подвинуть знак",
    "seamarkSave"            => "Сохранить знак",
    "seamarkCategory"        => "Категория знака",
    "seamarkType"            => "Форма знака",
    "seamarkName"            => "Наименование знака",
    "comboUnknown"           => "Не выбрано - - - - - - - - - - -",
    "comboSafeWater"         => "Чистая вода",
    "comboPort"              => "Левая сторона",
    "comboStarboard"         => "Правая сторона",
    "comboPrefPort"          => "Основной фарватер слева",
    "comboPrefStarboard"     => "Основной фарватер справа",
    "comboNorth"             => "Северный кардинальный знак",
    "comboEast"              => "Восточный кардинальный знак",
    "comboSouth"             => "Южный кардинальный знак",
    "comboWest"              => "Западный кардинальный знак",
    "comboIsolatedDanger"    => "Изолированная опасность",
    "comboSpecialPurpose"    => "Знак специального назначения",
    "sphere"                 => "Сферический",
    "conical"                => "Конический",
    "can"                    => "Тупоконечный",
    "barrel"                 => "Бочкообразный",
    "pillar"                 => "Столбовидный",
    "spar"                   => "Вехообразный",
    "beacon"                 => "Бакен",
    "topmark"                => "Верхняя фигура",
    "radar"                  => "Радио-отражатель",
    "lighted"                => "Светится",
    "fogsignal"              => "Туманный ревун",
    "miscItems"              => "Другие <br>свойства",
    "colour"                 => "Цвет",
    "red"                    => "красный",
    "yellow"                 => "жёлтый",
    "character"              => "Буква",
    "period"                 => "Период",
    "haveAccount"            => "Вы ещё не зарегистрированы в OSM?<br/>",

    //Network -------------------------------------------------------
    "send401"                => "Облом: неверное имя или пароль!",
    "send404"                => "Облом: сервер базы OSM не отвечает!",
    
    // Urls ---------------------------------------------------------
    "UrlOSM"                 => "http://openstreetmap.org",
    "UrlOSMWiki_Hauptseite"  => "http://wiki.openstreetmap.org/wiki/Ru:Main_Page",
    "UrlOSMWiki_OpenSeaMap"  => "http://wiki.openstreetmap.org/wiki/Ru:OpenSeaMap",

    // Legende ------------------------------------------------------
    "Legende"                => "Условные обозначения",
    "Seezeichen"             => "Морские знаки",
    "Leuchtfeuer"            => "Маяки",
    "BrückenSchleusen"       => "Мосты/шлюзы",
    //Harbour
    "harbour"                => "Гавань",
    "breakwater"             => "Волнорез",
    "pier"                   => "Причал",
    "crane"                  => "Кран",
    "slipway"                => "Стапель",
    "harbour_master"         => "Начальник порта",
    "waste_disposal"         => "Сброс отходов",
    //Seamarks
    "safe_water"             => "Знак чистой воды",
    "lateral_port"           => "Знак левой стороны",
    "lateral_starboard"      => "Знак правой стороны",
    "lateral_pref_port"      => "Основной фарватер слева",
    "lateral_pref_starboard" => "Основной фарватер справа",
    "cardinal_north"         => "Северный кардинальный знак",
    "cardinal_east"          => "Восточный кардинальный знак",
    "cardinal_south"         => "Южный кардинальный знак",
    "cardinal_west"          => "Западный кардинальный знак",
    "isolated_danger"        => "Знак изолированной опасности",
    "special_purpose"        => "Знак специального назначения",
    //Lights
    "lighthouse"             => "Маяк",
    "beacon_green"           => "Зелёный бакен",
    "beacon_red"             => "Красный бакен",
    "beacon_white"           => "Белый бакен",
    //Locks
    "lock_gate"              => "Вход в шлюз",
    "lock"                   => "Шлюз",
    "wier_small"             => "Плотина (маленькая)",
    "wier_big"               => "Плотина (большая)",
);

?>
